### ISSUE TITLE
Projeto presente em qual curso?

### ISSUE THREAD

**Issue by camilapessoa** [alura-cursos/blog-do-codigo#5]
Boa tarde, gostaria de uma informação sobre o projeto. Este projeto foi utilizado em qual curso? Apenas no JWT?

Grata.

**Comment by AndrewIjano** [comment]
Olá, @camilapessoa! Até onde eu sei, sim. Ainda, variações desse projeto foram utilizadas em duas sequências do curso (sobre refresh tokens e autorização).

**Comment by camilapessoa** [comment]
Obrigada pela resposta, Andrew! Minha pergunta se relaciona mais ao CRUD inicial. Há um curso ou projeto anterior em que você trabalha com o início do projeto? 

Grata e desculpe o incômodo.

**Comment by AndrewIjano** [comment]
Olá, @camilapessoa, sem problemas 😁 .

Não, como a ideia do curso é apresentar os tópicos de segurança e autenticação, o projeto já traz o CRUD inicial pronto. Idealmente, a teoria de como criar esse CRUD é dada nos cursos anteriores da formação de NodeJS: https://www.alura.com.br/formacao-node-js-12.

Os projetos usados nos cursos anteriores podem ter sido diferentes mas imagino que o conteúdo deva ser bem parecido.

**Comment by camilapessoa** [comment]
Muitíssimo obrigada, Andrew! Tanto pelo tempo como disposição para responder!!
